item-app-1  | 
item-app-1  | > docker-software-delivery@1.0.0 start /app
item-db-1   | 2024-06-22T08:52:54.944+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=1ad1fb29b280
item-db-1   | 2024-06-22T08:52:54.944+0000 I CONTROL  [initandlisten] db version v3.6.23
item-db-1   | 2024-06-22T08:52:54.944+0000 I CONTROL  [initandlisten] git version: d352e6a4764659e0d0350ce77279de3c1f243e5c
item-db-1   | 2024-06-22T08:52:54.944+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
item-db-1   | 2024-06-22T08:52:54.944+0000 I CONTROL  [initandlisten] allocator: tcmalloc
item-db-1   | 2024-06-22T08:52:54.945+0000 I CONTROL  [initandlisten] modules: none
item-db-1   | 2024-06-22T08:52:54.945+0000 I CONTROL  [initandlisten] build environment:
item-db-1   | 2024-06-22T08:52:54.945+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
item-db-1   | 2024-06-22T08:52:54.945+0000 I CONTROL  [initandlisten]     distarch: aarch64
item-db-1   | 2024-06-22T08:52:54.945+0000 I CONTROL  [initandlisten]     target_arch: aarch64
item-db-1   | 2024-06-22T08:52:54.945+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
item-db-1   | 2024-06-22T08:52:54.945+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
item-db-1   | 2024-06-22T08:52:54.945+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=2112M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
item-db-1   | 2024-06-22T08:52:55.335+0000 I STORAGE  [initandlisten] WiredTiger message [1719046375:335382][1:0xffffa82d5000], txn-recover: Main recovery loop: starting at 5/4736
item-db-1   | 2024-06-22T08:52:55.417+0000 I STORAGE  [initandlisten] WiredTiger message [1719046375:417881][1:0xffffa82d5000], txn-recover: Recovering log 5 through 6
item-db-1   | 2024-06-22T08:52:55.474+0000 I STORAGE  [initandlisten] WiredTiger message [1719046375:474387][1:0xffffa82d5000], txn-recover: Recovering log 6 through 6
item-db-1   | 2024-06-22T08:52:55.519+0000 I STORAGE  [initandlisten] WiredTiger message [1719046375:519406][1:0xffffa82d5000], txn-recover: Set global recovery timestamp: 0
item-db-1   | 2024-06-22T08:52:55.539+0000 I CONTROL  [initandlisten] 
item-db-1   | 2024-06-22T08:52:55.539+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
item-db-1   | 2024-06-22T08:52:55.539+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
item-db-1   | 2024-06-22T08:52:55.539+0000 I CONTROL  [initandlisten] 
item-db-1   | 2024-06-22T08:52:55.539+0000 I CONTROL  [initandlisten] 
item-db-1   | 2024-06-22T08:52:55.539+0000 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. rlimits set to 20990 processes, 1048576 files. Number of processes should be at least 524288 : 0.5 times number of files.
item-db-1   | 2024-06-22T08:52:55.544+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
item-db-1   | 2024-06-22T08:52:55.544+0000 I NETWORK  [initandlisten] listening via socket bound to 0.0.0.0
item-db-1   | 2024-06-22T08:52:55.545+0000 I NETWORK  [initandlisten] listening via socket bound to /tmp/mongodb-27017.sock
item-db-1   | 2024-06-22T08:52:55.545+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
item-db-1   | 2024-06-22T08:52:55.938+0000 I NETWORK  [listener] connection accepted from 192.168.223.3:43556 #1 (1 connection now open)
item-db-1   | 2024-06-22T08:52:55.940+0000 I NETWORK  [conn1] received client metadata from 192.168.223.3:43556 conn1: { driver: { name: "nodejs", version: "2.2.36" }, os: { type: "Linux", name: "linux", architecture: "arm64", version: "6.7.10-orbstack-00140-g04c64cb35a2e" }, platform: "Node.js v14.21.3, LE, mongodb-core: 2.1.20" }
item-app-1  | > node ./bin/www
item-app-1  | 
item-app-1  | NODE_ENV: production
item-app-1  | /app/node_modules/mongodb/lib/mongo_client.js:421
item-app-1  |           throw err
item-app-1  |           ^
item-app-1  | 
item-app-1  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 192.168.223.2:27017
item-app-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
item-app-1  |   name: 'MongoError'
item-app-1  | }]
item-app-1  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
item-app-1  |     at Pool.emit (events.js:400:28)
item-app-1  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
item-app-1  |     at Object.onceWrapper (events.js:520:26)
item-app-1  |     at Connection.emit...
item-app-1  |     at /app/app.js:24:10
item-app-1  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
item-app-1  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
item-app-1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
item-app-1  |   generatedMessage: true,
item-app-1  |   code: 'ERR_ASSERTION',
item-app-1  |   actual: null,
item-app-1  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 192.168.223.2:27017
item-app-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
item-app-1  |     name: 'MongoError'
item-app-1  |   }]
item-app-1  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
item-app-1  |       at Pool.emit (events.js:400:28)
item-app-1  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
item-app-1  |       at Object.onceWrapper (events.js:520:26)
item-app-1  |       at Connection.emit (events.js:400:28)
item-app-1  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
item-app-1  |       at Object.onceWrapper (events.js:520:26)
item-app-1  |       at Socket.emit (events.js:400:28)
item-app-1  |       at emitErrorNT (internal/streams/destroy.js:106:8)
item-app-1  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
item-app-1  |   operator: '=='
item-app-1  | }
item-app-1  | npm ERR! code ELIFECYCLE
item-app-1  | npm ERR! errno 1
item-app-1  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
item-app-1  | npm ERR! Exit status 1
item-app-1  | npm ERR! 
item-app-1  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
item-app-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
item-app-1  | 
item-app-1  | npm ERR! A complete log of this run can be found in:
item-app-1  | npm ERR!     /root/.npm/_logs/2024-06-22T08_52_55_343Z-debug.log
item-app-1  | 
item-app-1  | > docker-software-delivery@1.0.0 start /app
item-app-1  | > node ./bin/www
item-app-1  | 
item-app-1  | NODE_ENV: production
item-app-1  | Connected to database
